In [1]:
#import the required libraries
import numpy as np

# Step 1 : Read the Data!

In [ ]:
#give path of the source-file and store that path in a variable named census
census = 'makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [ ]:
data = np.genfromtxt(census, delimiter=',', skip_header=1)
print(" census ", data)

 census  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [ ]:
#print the type of data
print(type(data))

<class 'numpy.ndarray'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [ ]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [ ]:
np.concatenate((data,new_record))

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [ ]:
age=np.array(data[:,0])

Find the max age and store it in a variable called 'max_age'.



In [ ]:
#print the max_age
max_age=np.max(age)
print(max_age)

90.0


Find the min age and store it in a variable called 'min_age'.

In [ ]:
#print the min_age
min_age=np.min(age)
print(min_age)

17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [ ]:
#print the age_mean
age_mean=np.mean(age)
print(age_mean)

38.051


Find the standard deviation of the age and store it in a variable called 'age_std'

In [ ]:
#print the age_std
age_std=np.std(age)
print(age_std)

13.342803266180612


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [ ]:
race_0=data[data[:,2]==0]
race_1=data[data[:,2]==1]
race_2=data[data[:,2]==2]
race_3=data[data[:,2]==3]
race_4=data[data[:,2]==4]

In [ ]:
len(race_0)
len(race_1)
len(race_2)
len(race_3)
len(race_4)

847

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [ ]:
#len_0
len(race_0)

10

In [ ]:
#len_1
len(race_1)

27

In [ ]:
#len_2
len(race_2)

110

In [ ]:
#len_3
len(race_3)

6

In [ ]:
#len_4
len(race_4)

847

Find out which is the race with the minimum no. of citizens

In [ ]:
np.min(race_0)

0.0

In [ ]:
np.min(race_1)

0.0

In [ ]:
np.min(race_2)

0.0

In [ ]:
np.min(race_3)

0.0

In [ ]:
np.min(race_4)

0.0

Find out which is the race with the minimum no. of citizens

In [ ]:
np.min(race_0)

0.0

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [ ]:
minority_race=np.min(race_0)
print(minority_race)

0.0


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [ ]:
#from age column, filter out age data > 60
np.array(data[:,0])
senior_citizens=data[data[:,0]>60]

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [ ]:
np.sum(senior_citizens[:,6])

1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [ ]:
len(senior_citizens)

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [ ]:
avg_working_hours=np.sum(senior_citizens[:,6])/len(senior_citizens)

31.42622950819672


e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [ ]:
print(avg_working_hours)

31.42622950819672


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [ ]:
high=data[data[:,1]>10]
low=data[data[:,1]<=10]

taFind the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [ ]:
avg_pay_high=np.mean(high[:,7])
avg_pay_low=np.mean(low[:,7])

In [ ]:
print(avg_pay_high)
print(avg_pay_low)

0.42813455657492355
0.13670133729569092
